name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch:

permissions:
  contents: write  # IZIN supaya bisa push ke repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: dexccv
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg

      - name: Commit and push generated files
        run: |
          mkdir -p output
          mv dist/* output/
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "update pacman contribution graph" || echo "no changes to commit"
          git push
